### PR TITLE
Removes PII from seeds file, updates Gemfile, and cleans up documentatio...

### PR DESCRIPTION
**Pull request by carlosplusplus**
It's funny how I always find myself back on this project.

Remembered in my sleep that our seeds file had **[PII](http://en.wikipedia.org/wiki/Personally_identifiable_information)** in it, so this PR removes it.
Cleaned up the generation of the data as well by adding in the **[faker](https://github.com/stympy/faker)** gem.

Specified Ruby 1.9.3 and cleaned up the Rdoc README file.

Look good to you, @awaxman11 // @chhhris // @dmanaster? :smile:

acdc

### CODE REVIEW

**Comment by carlosplusplus** [comment]
Hey, a little over 2 yrs later --- additional ping please to remove this PII? Thanks!

**Comment by JessRudder** [comment]
@jmburges @aviflombaum Gonzo asked if we could get this PR merged in to remove their personal data.  I tried, but, I do not have access here.  Any chance one of you do?  The repo has no public members, so, it's not clear who owns it.

**Comment by jmburges** [comment]
Thanks @JessRudder, I'll have to grab Avi to merge this in.

**Comment by chhhris** [comment]
@carlosplusplus it's happening!

**Comment by carlosplusplus** [comment]
Only took... 2 1/2 years haha. 😂

**Comment by maxjacobson** [comment]
here's to 2 1/2 more 🍻

**Comment by aviflombaum** [comment]
Hi @carlosplusplus @maxjacobson @chhhris h/t @jmburges progress!!! 

🤘

**Comment by chrisgonzgonz** [comment]
thanks @aviflombaum ! 

<3 the class of 002

**Pull request merged**
